name: Run Tests

on:
  workflow_run:
    workflows: ["maven build"]
    types:
      - completed

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 11
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Run Tests
      run: mvn -B test
